apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: veba-ps-enter-mm-trigger
  labels:
    app: veba-ui
  namespace: vmware-functions
spec:
  broker: default
  filter:
    attributes:
        type: com.vmware.event.router/event
        subject: EnteredMaintenanceModeEvent
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: veba-ps-enter-mm-service
