apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: veba-ps-enter-mm-service
  labels:
    app: veba-ui
  namespace: vmware-functions
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/darrylcauldwell/veba-ps-enter-mm:1.0
          envFrom:
            - secretRef:
                name: veba-knative-mm-vrops
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: veba-ps-enter-mm-trigger
  labels:
    app: veba-ui
  namespace: vmware-functions
spec:
  broker: default
  filter:
    attributes:
        type: com.vmware.event.router/event
        subject: EnteredMaintenanceModeEvent
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: veba-ps-enter-mm-service